# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pasos', models.IntegerField(blank=True, null=True)),
                ('flujos_id', models.IntegerField(blank=True, null=True)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
