# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasos',
            name='id_pasos',
        ),
    ]
