# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-03 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_flujo_de_trabajo_solicitudes_solicitudes_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujo_de_trabajo',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
