# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-08 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_auto_20161103_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
