# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_auto_20161108_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_logs',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
