# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_auto_20161110_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
