from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.inicio, name='inicio'),
    url(r'^registro/$', views.registro, name='registro'),
    url(r'^solicitudes/$', views.home, name='home'),
    url(r'^solicitudes/pasadas/$', views.solicitudesPasadas, name='solicitudesPasadas'),
    url(r'^solicitudes/encargadas/$', views.solicitudesEncargadas, name='solicitudesEncargadas'),
    url(r'^solicitudes/eliminar/(?P<idSolicitud>\d+)/$', views.eliminarSolicitud, name='eliminarSolicitud'),
    url(r'^cerrarSesion/$', views.cerrarSesion, name='cerrarSesion'),
    url(r'^administracion/workflow/list/$', views.workflowList, name='workflowList'),
    url(r'^administracion/workflow/nuevo/$', views.nuevoWorkflow, name='nuevoWorkflow'),
    url(r'^administracion/workflow/editarWorkflow/(?P<idWorkflow>\d+)$', views.editarWorkflow, name='editarWorkflow'),
    url(r'^administracion/workflow/desactivarWorkflow/(?P<idWorkflow>\d+)$', views.desactivarWorkflow, name='desactivarWorkflow'),
    url(r'^administracion/workflow/activarWorkflow/(?P<idWorkflow>\d+)$', views.activarWorkflow, name='activarWorkflow'),
    url(r'^administracion/solicitudes/agente/$', views.solicitudesAgentes, name='solicitudesAgente'),
    url(r'^administracion/workflow/(?P<id>\d+)/pasos/$', views.verPasos, name='verPasos'),
    url(r'^administracion/workflow/(?P<id>\d+)/pasos/nuevo$', views.nuevoPaso, name='nuevoPaso'),
    url(r'^administracion/workflow/(?P<idWorkflow>\d+)/pasos/borrar/(?P<idPaso>\d+)$', views.eliminarPaso, name='eliminarPaso'),
    url(r'^administracion/workflow/(?P<idWorkflow>\d+)/pasos/editar/(?P<idPaso>\d+)$', views.editarPaso, name='editarPaso'),
    url(r'^administracion/usuarios/$', views.verUsuarios, name='verUsuarios'),
    url(r'^administracion/usuarios/nuevo/$', views.nuevoUsuario, name='nuevoUsuario'),
    url(r'^administracion/usuarios/editar/(?P<idUsuario>\d+)$', views.editarUsuario, name='editarUsuario'),
    url(r'^administracion/usuarios/borrar/(?P<idUsuario>\d+)$', views.eliminarUsuario, name='eliminarUsuario'),
    url(r'^administracion/usuarios/activar/(?P<idUsuario>\d+)$', views.activarUsuario, name='activarUsuario'),
    url(r'^solicitudes/(?P<idProceso>\d+)/crear/$', views.crearSolicitud, name='crearSolicitud'),
    url(r'^solicitudes/(?P<idSolicitud>\d+)/formulario/$', views.formulario, name='formulario'),
    url(r'^solicitudes/(?P<idLog>\d+)/formulario/enviar/$', views.enviarFormulario, name='enviarFormulario'),
    url(r'^solicitudes/(?P<idLog>\d+)/formulario/devolver/$', views.devolverFormulario, name='devolverFormulario'),
    url(r'^solicitudes/(?P<idLog>\d+)/formulario/guardar/$', views.guardarFormulario, name='guardarFormulario'),
    url(r'^solicitudes/(?P<idSolicitud>\d+)/historico/$', views.historico, name='historico'),
    url(r'^administracion/reporteSolicitudesAbiertas/$', views.reporteSolicitudesAbiertas, name='reporteSolicitudesAbiertas'),
    url(r'^administracion/indicadores/$', views.indicadores, name='indicadores'),
]